name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reservation/pom.xml
          mvn clean package -f ./assigningstatus/pom.xml
          mvn clean package -f ./room/pom.xml
          mvn clean package -f ./cleaningstatus/pom.xml

      - name: Docker Build and push for Reservation
        uses: docker/build-push-action@v4
        with:
          context: ./reservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation:latest
            ghcr.io/${{ github.repository }}/reservation:${{ github.ref_name }}
            
      - name: Docker Build and push for Assigningstatus
        uses: docker/build-push-action@v4
        with:
          context: ./assigningstatus
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/assigningstatus:latest
            ghcr.io/${{ github.repository }}/assigningstatus:${{ github.ref_name }}
            
      - name: Docker Build and push for Room
        uses: docker/build-push-action@v4
        with:
          context: ./room
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/room:latest
            ghcr.io/${{ github.repository }}/room:${{ github.ref_name }}
            
      - name: Docker Build and push for Cleaningstatus
        uses: docker/build-push-action@v4
        with:
          context: ./cleaningstatus
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cleaningstatus:latest
            ghcr.io/${{ github.repository }}/cleaningstatus:${{ github.ref_name }}
            
