apiVersion: apps/v1
kind: Deployment
metadata:
  name: assigningstatus
  labels:
    app: assigningstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assigningstatus
  template:
    metadata:
      labels:
        app: assigningstatus
    spec:
      containers:
        - name: assigningstatus
          image: "username/assigningstatus:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
