apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaningstatus
  labels:
    app: cleaningstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleaningstatus
  template:
    metadata:
      labels:
        app: cleaningstatus
    spec:
      containers:
        - name: cleaningstatus
          image: "username/cleaningstatus:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
